/**
 * galaxy inc.
 * meetup client for android
 */
package com.galaxy.meetup.server.client.domain;

import java.util.List;

/**
 * 
 * @author sihai
 * 
 */
public class HangoutData extends GenericJson {

	public HangoutDataBroadcastDetails broadcastDetails;
	public String broadcastId;
	public String broadcastTitle;
	public String eventId;
	public List hangoutMediaDetails;
	public String hashedRoomId;
	public Boolean idIsAutogenerated;
	public Boolean isActive;
	public Boolean isNoMinors;
	public Boolean isSelfPost;
	public Boolean isViewOnly;
	public String joinType;
	public Integer maxAttendees;
	public List notificationId;
	public List occupant;
	public List occupantEver;
	public String preferredLanguage;
	public String region;
	public String roomDomain;
	public String roomId;
	public String subject;
	public String topic;
	public Boolean topicMaybeNsfw;
	public String topicUrl;
	public String type;
	public String url;

	public HangoutDataBroadcastDetails getBroadcastDetails() {
		return broadcastDetails;
	}

	public void setBroadcastDetails(HangoutDataBroadcastDetails broadcastDetails) {
		this.broadcastDetails = broadcastDetails;
	}

	public String getBroadcastId() {
		return broadcastId;
	}

	public void setBroadcastId(String broadcastId) {
		this.broadcastId = broadcastId;
	}

	public String getBroadcastTitle() {
		return broadcastTitle;
	}

	public void setBroadcastTitle(String broadcastTitle) {
		this.broadcastTitle = broadcastTitle;
	}

	public String getEventId() {
		return eventId;
	}

	public void setEventId(String eventId) {
		this.eventId = eventId;
	}

	public List getHangoutMediaDetails() {
		return hangoutMediaDetails;
	}

	public void setHangoutMediaDetails(List hangoutMediaDetails) {
		this.hangoutMediaDetails = hangoutMediaDetails;
	}

	public String getHashedRoomId() {
		return hashedRoomId;
	}

	public void setHashedRoomId(String hashedRoomId) {
		this.hashedRoomId = hashedRoomId;
	}

	public Boolean getIdIsAutogenerated() {
		return idIsAutogenerated;
	}

	public void setIdIsAutogenerated(Boolean idIsAutogenerated) {
		this.idIsAutogenerated = idIsAutogenerated;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Boolean getIsNoMinors() {
		return isNoMinors;
	}

	public void setIsNoMinors(Boolean isNoMinors) {
		this.isNoMinors = isNoMinors;
	}

	public Boolean getIsSelfPost() {
		return isSelfPost;
	}

	public void setIsSelfPost(Boolean isSelfPost) {
		this.isSelfPost = isSelfPost;
	}

	public Boolean getIsViewOnly() {
		return isViewOnly;
	}

	public void setIsViewOnly(Boolean isViewOnly) {
		this.isViewOnly = isViewOnly;
	}

	public String getJoinType() {
		return joinType;
	}

	public void setJoinType(String joinType) {
		this.joinType = joinType;
	}

	public Integer getMaxAttendees() {
		return maxAttendees;
	}

	public void setMaxAttendees(Integer maxAttendees) {
		this.maxAttendees = maxAttendees;
	}

	public List getNotificationId() {
		return notificationId;
	}

	public void setNotificationId(List notificationId) {
		this.notificationId = notificationId;
	}

	public List getOccupant() {
		return occupant;
	}

	public void setOccupant(List occupant) {
		this.occupant = occupant;
	}

	public List getOccupantEver() {
		return occupantEver;
	}

	public void setOccupantEver(List occupantEver) {
		this.occupantEver = occupantEver;
	}

	public String getPreferredLanguage() {
		return preferredLanguage;
	}

	public void setPreferredLanguage(String preferredLanguage) {
		this.preferredLanguage = preferredLanguage;
	}

	public String getRegion() {
		return region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getRoomDomain() {
		return roomDomain;
	}

	public void setRoomDomain(String roomDomain) {
		this.roomDomain = roomDomain;
	}

	public String getRoomId() {
		return roomId;
	}

	public void setRoomId(String roomId) {
		this.roomId = roomId;
	}

	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getTopic() {
		return topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	public Boolean getTopicMaybeNsfw() {
		return topicMaybeNsfw;
	}

	public void setTopicMaybeNsfw(Boolean topicMaybeNsfw) {
		this.topicMaybeNsfw = topicMaybeNsfw;
	}

	public String getTopicUrl() {
		return topicUrl;
	}

	public void setTopicUrl(String topicUrl) {
		this.topicUrl = topicUrl;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
}
